### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by mattmeye** [davidecavaliere/serverless-api-decorators#1]
Do you still working on the project?

**Comment by davidecavaliere** [comment]
Hello Matt,

yes I'm still working on the project although I'm splitting the serverless plugin and the decorators part into separate projects. 

Why you're asking?

**Comment by mattmeye** [comment]
Hello David,

I'm currently experimenting with serverless and try to figure out how it can be handled in bigger projects. I think its impractical to maintain serverless.yml by hand. With the decorator approach i could kill this and i'm able to maintain every function (and its context) in a seperate file. 
I have seen that https://github.com/honerlaw/serverless-inversify-util have the same approach, but i'm struggling to get things started (serverelss-inversify-util & serverless-api-decorators).

I think it is very good that you want to split your project. Do you already have somthing to look at?

Kind regards,
Matt

**Comment by davidecavaliere** [comment]
thanks for your interest Matt. I do already have some working software. I
haven't shared anything yet because of the lack of proper documentation and
some missing features. there will be two packages: one is the sls plugin,
the other is the decorators one. unfortunately i will not be able to
publish anything before the end of the next week because I'm aboard at the
moment.
would you like to contribute?

**Comment by mattmeye** [comment]
That sounds very good! I am looking for your next release. If I have the opportunity, I will be happy to contribute.

**Comment by dbartholomae** [comment]
Interested as well! :)

**Comment by davidecavaliere** [comment]
Hello everyone and thanks for you interest. 

I'm not maintaining this project anymore as I split  it up into different repos/packages.

You can find them at https://github.com/davidecavaliere/-microgamma 

Sorry no instructions on how to use it yet but you can find a complete working example at https://github.com/davidecavaliere/bazooka-services

Also there no README yet. I apologize but I don't have much time to make everything.

Anyway you can contact me for any question.
