### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by mikecann** [davidecavaliere/serverless-api-decorators#2]
This is a really interesting project. 

I would suggest rather than writing the validation and DI part yourself leverage other well-tested projects such as TypeDI and class-validator with class-transformer.

Continue the good work tho, ill be keeping an eye on this.

It could be really interesting in the future to use this structure to auto-generate a strongly typed client API

**Comment by davidecavaliere** [comment]
It's been a long time. Thanks for your suggestions, I kind of followed them. 
I'm not maintaining this anymore. 
If you're still interested you can find the new work at https://github.com/davidecavaliere/-microgamma
